import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Activity, Rocket, TrendingUp, DollarSign, BarChart, CheckCircle, Info, HelpCircle, X } from 'lucide-react';

const API_BASE = 'http://localhost:8000';

const HelpModal = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    const paramsHelp = [
        { label: 'QIB (x)', def: 'Qualified Institutional Buyers subscription.', ex: '4.18x means QIBs bid for 4.18 times the shares offered in their category.' },
        { label: 'NII (x)', def: 'Non-Institutional Investors subscription.', ex: '1.60x means NIIs/HNIs bid for 1.60 times the offered shares.' },
        { label: 'Retail (x)', def: 'Retail Individual Investors subscription.', ex: '1.03x means the retail portion is fully subscribed.' },
        { label: 'Total Sub (x)', def: 'Cumulative subscription across all categories.', ex: '2.66x indicates moderate overall market interest.' },
        { label: 'Size (₹ Cr)', def: 'Total amount of money being raised.', ex: '₹2834 Cr suggests a mid-to-large-cap listing.' },
        { label: 'P/E Ratio', def: 'Price-to-Earnings ratio relative to profits.', ex: '85.0 suggests aggressive growth pricing.' },
        { label: 'Revenue (₹ Cr)', def: 'Annual income generated by the company.', ex: '₹2765 Cr for the last financial year.' },
        { label: 'PAT (₹ Cr)', def: 'Profit After Tax.', ex: '₹220 Cr indicates the net profit after all expenses.' },
        { label: 'ROE (%)', def: 'Return on Equity (Profit/Equity).', ex: '11% means the company generates ₹11 profit per ₹100 equity.' },
        { label: 'ROCE (%)', def: 'Return on Capital Employed.', ex: '12.9% shows efficiency in using invested capital.' },
        { label: 'Margin (%)', def: 'Net Profit Margin (PAT / Revenue).', ex: '8% profit for every ₹100 earned.' },
        { label: 'Growth (%)', def: 'Annual revenue growth rate.', ex: '18% year-over-year income increase.' },
    ];

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
            <div className="bg-white dark:bg-dark-card w-full max-w-4xl max-h-[85vh] rounded-[2.5rem] border border-gray-100 dark:border-dark-border shadow-2xl overflow-hidden flex flex-col">
                <div className="p-8 border-b border-gray-100 dark:border-dark-border flex justify-between items-center bg-gray-50/50 dark:bg-dark-bg/50">
                    <div className="flex items-center gap-3">
                        <div className="p-3 bg-primary-100 dark:bg-primary-900/30 rounded-2xl">
                            <HelpCircle className="w-6 h-6 text-primary-600" />
                        </div>
                        <h2 className="text-2xl font-black text-gray-900 dark:text-white">Metric Definitions</h2>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-gray-200 dark:hover:bg-dark-card rounded-full transition-colors">
                        <X className="w-6 h-6 text-gray-400" />
                    </button>
                </div>
                <div className="p-8 overflow-y-auto grid grid-cols-1 md:grid-cols-2 gap-6">
                    {paramsHelp.map(item => (
                        <div key={item.label} className="p-6 bg-gray-50 dark:bg-dark-bg/30 rounded-3xl border border-gray-100 dark:border-dark-border hover:border-primary-500/30 transition-colors">
                            <h3 className="font-black text-primary-600 mb-2 uppercase tracking-wider">{item.label}</h3>
                            <p className="text-sm text-gray-900 dark:text-white font-bold mb-2">{item.def}</p>
                            <div className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed italic">
                                <strong>Example:</strong> {item.ex}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

const MetricCard = ({ label, value, subtext, color, icon: Icon, progress }) => (
    <div className="bg-white dark:bg-dark-card p-8 rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-sm hover:shadow-xl transition-all duration-300 group">
        <div className="flex justify-between items-start mb-6">
            <div className={`p-4 rounded-2xl group-hover:scale-110 transition-transform`} style={{ backgroundColor: `${color}15` }}>
                <Icon className="w-6 h-6" style={{ color: color }} />
            </div>
            <div className="text-right">
                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">{label}</p>
                <h3 className="text-3xl font-black text-gray-900 dark:text-white leading-none">{value}</h3>
            </div>
        </div>
        <div className="space-y-4">
            <div className="h-2 bg-gray-100 dark:bg-dark-bg rounded-full overflow-hidden">
                <div
                    className="h-full rounded-full transition-all duration-1000 ease-out"
                    style={{ width: `${Math.min(progress, 100)}%`, backgroundColor: color }}
                />
            </div>
            <p className="text-[11px] font-bold text-gray-500 dark:text-gray-400 tracking-wide uppercase">{subtext}</p>
        </div>
    </div>
);

export const Analysis = ({ initialParams }) => {
    const [params, setParams] = useState({
        qib: 4.41, nii: 0.80, retail: 1.08, total_sub: 2.81,
        issue_size: 2833.9, pe_ratio: 65.5, revenue: 2816.0,
        pat: 12.6, roe: 3.62, roce: 14.40, profit_margin: 17.40,
        revenue_growth: 26.0
    });

    const [results, setResults] = useState(null);
    const [loading, setLoading] = useState(false);
    const [isHelpOpen, setIsHelpOpen] = useState(false);
    const [companyName, setCompanyName] = useState('');
    const [actualGain, setActualGain] = useState(null);

    // Update params and auto-trigger analysis when initialParams changes
    useEffect(() => {
        if (initialParams) {
            setParams(initialParams);
            setCompanyName(initialParams.company_name || '');
            setActualGain(initialParams.actual_gain ?? null);
            setResults(null);

            // Auto-trigger analysis for the newly selected IPO
            const autoAnalyze = async () => {
                setLoading(true);
                try {
                    // Strip non-numerical fields for API
                    const { company_name, actual_gain, ...apiParams } = initialParams;
                    const response = await axios.post(`${API_BASE}/analyze`, apiParams);
                    setResults(response.data);
                } catch (error) {
                    console.error('Auto-analysis failed', error);
                }
                setLoading(false);
            };
            autoAnalyze();
        }
    }, [initialParams]);

    const handleAnalyze = async () => {
        setLoading(true);
        try {
            // Strip non-numerical fields for API
            const { company_name, actual_gain, ...apiParams } = params;
            const response = await axios.post(`${API_BASE}/analyze`, apiParams);
            setResults(response.data);
        } catch (error) {
            console.error('Analysis failed', error);
            alert('Failed to run analysis. Make sure the backend is running.');
        }
        setLoading(false);
    };

    const handleChange = (e) => {
        setParams({ ...params, [e.target.name]: parseFloat(e.target.value) || 0 });
    };

    // Helper to get a subtle background for the rating color
    const getBgColor = (hex) => `${hex}15`;

    return (
        /* Added extra top padding (pt-24) to ensure content starts well below the navbar [size: 6rem] */
        <div className="pt-24 pb-12 px-4 max-w-7xl mx-auto animate-fade-in space-y-12">
            <HelpModal isOpen={isHelpOpen} onClose={() => setIsHelpOpen(false)} />

            {/* Company Header Section */}
            {companyName && (
                <div className="flex items-center gap-4 animate-slide-up">
                    <div className="p-4 bg-primary-600 rounded-[1.5rem] shadow-xl shadow-primary-500/20">
                        <Rocket className="w-10 h-10 text-white" />
                    </div>
                    <div>
                        <h1 className="text-4xl md:text-6xl font-black text-gray-900 dark:text-white uppercase tracking-tight leading-none">
                            {companyName}
                        </h1>
                        <div className="flex items-center gap-2 mt-3">
                            <span className="px-3 py-1 bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 rounded-full text-[10px] font-black uppercase tracking-widest">
                                AI Auditing Active
                            </span>
                            <p className="text-xs text-gray-500 font-bold uppercase tracking-wider italic opacity-70">
                                Global Financial Intelligence Terminal
                            </p>
                        </div>
                    </div>
                </div>
            )}

            {/* Horizontal Input Section */}
            <div className="bg-white dark:bg-dark-card p-8 rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-2xl relative overflow-hidden">
                <div className="absolute top-0 left-0 w-2 h-full bg-primary-600"></div>

                <div className="space-y-8">
                    <div className="flex justify-between items-center">
                        <div className="flex items-center gap-2">
                            <h2 className="text-xl font-black text-gray-900 dark:text-white flex items-center gap-2 uppercase tracking-tight">
                                <Activity className="text-primary-600 w-5 h-5" /> IPO PARAMETERS
                            </h2>
                            <button
                                onClick={() => setIsHelpOpen(true)}
                                className="p-1 hover:bg-gray-100 dark:hover:bg-dark-bg rounded-full transition-colors text-gray-400 hover:text-primary-600"
                                title="Click for metric definitions"
                            >
                                <HelpCircle className="w-5 h-5" />
                            </button>
                        </div>
                    </div>

                    {/* Organized into 2 rows of 6 items each on large screens */}
                    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-6">
                        {[
                            { label: 'QIB (x)', name: 'qib' },
                            { label: 'NII (x)', name: 'nii' },
                            { label: 'Retail (x)', name: 'retail' },
                            { label: 'Total Sub (x)', name: 'total_sub' },
                            { label: 'Size (₹ Cr)', name: 'issue_size' },
                            { label: 'P/E Ratio', name: 'pe_ratio' },
                            { label: 'Revenue', name: 'revenue' },
                            { label: 'PAT (₹ Cr)', name: 'pat' },
                            { label: 'ROE (%)', name: 'roe' },
                            { label: 'ROCE (%)', name: 'roce' },
                            { label: 'Margin (%)', name: 'profit_margin' },
                            { label: 'Growth (%)', name: 'revenue_growth' },
                        ].map(field => (
                            <div key={field.name} className="space-y-1 group/field">
                                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] ml-1 opacity-70 group-hover/field:text-primary-600 transition-colors">
                                    {field.label}
                                </label>
                                <div className="relative">
                                    <input
                                        type="number"
                                        name={field.name}
                                        value={params[field.name]}
                                        onChange={(e) => {
                                            handleChange(e);
                                            // Optional: Debounced auto-analyze on manual change
                                        }}
                                        className="w-full bg-gray-50/50 dark:bg-dark-bg/50 border border-transparent dark:border-transparent hover:border-gray-200 dark:hover:border-dark-border rounded-xl px-4 py-2.5 transition-all outline-none dark:text-white font-black text-sm focus:bg-white dark:focus:bg-dark-bg focus:ring-4 focus:ring-primary-500/10"
                                        readOnly
                                    />
                                    <div className="absolute right-3 top-1/2 -translate-y-1/2 text-[10px] font-black text-primary-600/20 uppercase tracking-tighter">Verified</div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Results Section */}
            <div className="w-full">
                {!results ? (
                    <div className="h-64 flex flex-col items-center justify-center text-center p-12 bg-gray-50 dark:bg-dark-card/30 rounded-3xl border-2 border-dashed border-gray-200 dark:border-dark-border">
                        <div className="p-4 bg-primary-100 dark:bg-primary-900/30 rounded-full mb-4 animate-bounce">
                            <Info className="w-8 h-8 text-primary-600" />
                        </div>
                        <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Ready for Analysis</h3>
                        <p className="text-gray-600 dark:text-gray-400 max-w-xs">Click Analyze to see AI predictions based on these metrics.</p>
                    </div>
                ) : (
                    <div className="space-y-8 animate-fade-in">
                        {/* Rating Hero Card */}
                        <div
                            className="relative overflow-hidden rounded-[3rem] p-12 text-white shadow-2xl transition-all duration-700 hover:scale-[1.01]"
                            style={{ backgroundColor: results.rating_color }}
                        >
                            <div className="absolute top-0 right-0 p-12 opacity-10 pointer-events-none">
                                <Rocket className="w-80 h-80 rotate-12" />
                            </div>

                            <div className="relative z-10">
                                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/20 backdrop-blur-md border border-white/30 mb-8">
                                    <CheckCircle className="w-4 h-4 text-white" />
                                    <span className="text-[10px] font-black uppercase tracking-[0.2em]">Verified AI Audit Score</span>
                                </div>

                                <div className="flex flex-col lg:flex-row items-center lg:items-end justify-between gap-12">
                                    <div className="text-center lg:text-left">
                                        <p className="text-[10px] font-black uppercase tracking-[0.3em] mb-4 opacity-70">Unified IPO Rating</p>
                                        <div className="flex items-baseline justify-center lg:justify-start">
                                            <span className="text-[12rem] font-black leading-none tracking-tighter">{results.unified_rating}</span>
                                            <span className="text-4xl font-bold opacity-40 ml-4 mb-6">/10</span>
                                        </div>
                                    </div>

                                    <div className="flex flex-col items-center lg:items-end text-center lg:text-right max-w-xl">
                                        <div className="px-12 py-5 bg-white text-gray-900 dark:bg-dark-card dark:text-white rounded-[2rem] text-4xl font-black mb-8 shadow-2xl uppercase tracking-tighter">
                                            {results.rating_label}
                                        </div>
                                        <p className="text-xl font-bold leading-tight opacity-95">
                                            {results.recommendation.split('.')[0]}.
                                        </p>
                                        <p className="text-sm font-medium opacity-70 mt-4 leading-relaxed line-clamp-2">
                                            Our neural engine indicates a {results.rating_label.toLowerCase()} performance based on historical sector trends and current market sentiment.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Backtest Analysis Card - Only shown if actualGain exists */}
                        {actualGain !== null && (
                            <div className="bg-white dark:bg-dark-card rounded-[3rem] border-4 border-dashed border-primary-500/20 p-12 relative overflow-hidden group">
                                <div className="absolute top-0 right-0 p-12 opacity-5 group-hover:scale-110 transition-transform">
                                    <BarChart className="w-48 h-48" />
                                </div>

                                <div className="relative z-10">
                                    <div className="flex items-center gap-3 mb-10">
                                        <div className="p-3 bg-primary-600 rounded-2xl shadow-lg">
                                            <Activity className="w-6 h-6 text-white" />
                                        </div>
                                        <div>
                                            <h2 className="text-2xl font-black text-gray-900 dark:text-white uppercase tracking-tight">Backtest Performance</h2>
                                            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mt-1">AI Prediction Accuracy Audit</p>
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                        <div className="p-8 bg-gray-50 dark:bg-dark-bg/50 rounded-[2rem] border border-gray-100 dark:border-dark-border group/card hover:border-primary-500/30 transition-colors">
                                            <p className="text-xs font-black text-gray-400 uppercase tracking-widest mb-2">TraQ AI Prediction</p>
                                            <h3 className="text-5xl font-black text-primary-600">+{results.listing_gain.toFixed(2)}%</h3>
                                            <div className="mt-6 flex items-center gap-2">
                                                <div className="w-full h-1.5 bg-gray-200 dark:bg-dark-border rounded-full overflow-hidden">
                                                    <div className="h-full bg-primary-500 rounded-full" style={{ width: `${Math.min(results.listing_gain, 100)}%` }}></div>
                                                </div>
                                            </div>
                                        </div>

                                        <div className="p-8 bg-primary-600 rounded-[2rem] text-white shadow-2xl shadow-primary-500/20 group/card relative overflow-hidden">
                                            <div className="absolute inset-0 bg-white/5 opacity-0 group-hover/card:opacity-100 transition-opacity"></div>
                                            <div className="relative z-10">
                                                <p className="text-xs font-black uppercase tracking-widest mb-2 opacity-80">Actual Listing Gain</p>
                                                <h3 className="text-5xl font-black">+{actualGain}%</h3>
                                                <div className="mt-6 flex items-center gap-2">
                                                    <div className="w-full h-1.5 bg-white/20 rounded-full overflow-hidden">
                                                        <div className="h-full bg-white rounded-full" style={{ width: `${Math.min(actualGain, 100)}%` }}></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="mt-10 p-6 bg-primary-50 dark:bg-primary-900/10 rounded-2xl flex items-center justify-between border border-primary-100 dark:border-primary-900/20">
                                        <div className="flex items-center gap-4">
                                            <div className="p-2 bg-primary-600 rounded-xl">
                                                <TrendingUp className="w-4 h-4 text-white" />
                                            </div>
                                            <p className="text-sm font-bold text-gray-900 dark:text-white">
                                                AI Variance: <span className="text-primary-600">{(actualGain - results.listing_gain).toFixed(2)}%</span>
                                            </p>
                                        </div>
                                        <div className="hidden sm:block text-[10px] font-black text-primary-600 uppercase tracking-widest">
                                            High Precision Model
                                        </div>
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* Grid Metrics with rating-influenced styling */}
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                            <MetricCard
                                label="Listing Gain"
                                value={`${results.listing_gain.toFixed(2)}%`}
                                subtext={results.gain_tag}
                                color={results.gain_color}
                                icon={Rocket}
                                progress={Math.abs(results.listing_gain)}
                            />
                            <MetricCard
                                label="Subscription Demand"
                                value={`${params.total_sub.toFixed(1)}x`}
                                subtext={`${results.demand_tier} Interest`}
                                color={results.demand_color}
                                icon={Activity}
                                progress={params.total_sub}
                            />
                            <MetricCard
                                label="Long-Term Gain"
                                value={`${results.longterm_gain.toFixed(1)}%`}
                                subtext="6-12 Month Projection"
                                color="#10b981"
                                icon={TrendingUp}
                                progress={results.longterm_gain}
                            />
                            <MetricCard
                                label="Financial Strength"
                                value={`${results.financial_rating.toFixed(1)}/10`}
                                subtext="Fundamental Analysis"
                                color="#8b5cf6"
                                icon={DollarSign}
                                progress={results.financial_rating * 10}
                            />
                            <MetricCard
                                label="Valuation PE"
                                value={`${results.pe_score.toFixed(1)}/10`}
                                subtext="Pricing Efficiency"
                                color="#3b82f6"
                                icon={BarChart}
                                progress={results.pe_score * 10}
                            />

                            {/* AI Rationale Box */}
                            <div className="lg:col-span-1 bg-white dark:bg-dark-card p-6 rounded-3xl border border-gray-100 dark:border-dark-border shadow-sm flex flex-col justify-center">
                                <div className="flex items-start gap-4">
                                    <div className="p-3 rounded-2xl" style={{ backgroundColor: getBgColor(results.rating_color) }}>
                                        <CheckCircle className="w-6 h-6" style={{ color: results.rating_color }} />
                                    </div>
                                    <div>
                                        <h4 className="font-bold text-gray-900 dark:text-white mb-1">AI Rationale</h4>
                                        <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">
                                            {results.recommendation}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};
