import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ModelEvaluationDashboard } from '../components/ModelEvaluationDashboard';
import { ArrowLeft, Microscope, Microscope as MicroscopeIcon } from 'lucide-react';

export const Research = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-dark-bg animate-fade-in pb-20 pt-28">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* 1. Page Header */}
                <div className="mb-12 flex flex-col md:flex-row md:items-end justify-between gap-8">
                    <div className="space-y-4">
                        <button 
                            onClick={() => navigate('/ipo')}
                            className="flex items-center gap-2 text-primary-600 font-black uppercase tracking-widest text-xs hover:gap-4 transition-all"
                        >
                            <ArrowLeft className="w-4 h-4" />
                            Back to IPO listings
                        </button>
                        <div className="flex items-center gap-6">
                            <div className="p-5 bg-primary-600 rounded-[2rem] shadow-2xl shadow-primary-500/20 text-white">
                                <MicroscopeIcon className="w-10 h-10" />
                            </div>
                            <div>
                                <h1 className="text-5xl md:text-6xl font-black text-gray-900 dark:text-white uppercase tracking-tighter leading-none">
                                    Research Intelligence
                                </h1>
                                <p className="text-xs font-bold text-gray-500 uppercase tracking-[0.3em] mt-2">
                                    Ensemble Model Intelligence & Performance Metrics
                                </p>
                            </div>
                        </div>
                    </div>
                    
                    <div className="flex items-center gap-4 p-6 bg-white dark:bg-dark-card rounded-[2.5rem] border border-gray-100 dark:border-dark-border shadow-xl">
                        <div className="text-right">
                            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest leading-tight">Live Core</p>
                            <p className="text-sm font-black text-primary-600 uppercase">Production Ready</p>
                        </div>
                        <div className="w-12 h-12 rounded-2xl bg-primary-50 dark:bg-primary-900/20 flex items-center justify-center">
                            <div className="w-3 h-3 bg-primary-600 rounded-full animate-ping"></div>
                        </div>
                    </div>
                </div>

                {/* 2. Main Dashboard Component */}
                <div className="bg-white dark:bg-dark-card rounded-[3.5rem] border border-gray-100 dark:border-dark-border shadow-2xl shadow-primary-500/5 overflow-hidden">
                    <div className="p-8 md:p-12 lg:p-20">
                        <ModelEvaluationDashboard />
                    </div>
                </div>

                {/* 3. Footer / Disclaimer */}
                <div className="mt-12 text-center max-w-3xl mx-auto space-y-4">
                    <p className="text-[10px] font-bold text-gray-400 uppercase tracking-[0.2em] leading-relaxed">
                        Data generated by the optimization script in /backend/scripts/optimize_ensemble.py. 
                        Performance metrics (MAE/R²) are calculated against the IPO_MasterDB historical dataset.
                    </p>
                </div>
            </div>
        </div>
    );
};
